home:
  path: /
  controller: App\Controller\HomeController::index
properties:
  path: /properties
  controller: App\Controller\PropertyController::index
property:
  path: /properties/{slug}.{id}
  controller: App\Controller\PropertyController::show
  requirements:
    slug: "[a-z0-9\\-]*"
