home:
  path: /
  controller: App\Controller\HomeController::index
properties.show:
  path: /properties
  controller: App\Controller\PropertyController::index
property.show:
  path: /properties/{slug}-{id}
  controller: App\Controller\PropertyController::show
  requirements:
    slug: "[a-z0-9\\-]*"
login:
  path: /login
  controller: App\Controller\SecurityController::login
logout:
  path: /logout


admin.properties.show:
  path: /admin
  controller: App\Controller\Admin\PropertyController::index
admin.property.new:
  path: /admin/properties/new
  controller: App\Controller\Admin\PropertyController::new
admin.property.edit:
  path: /admin/properties/{id}
  controller: App\Controller\Admin\PropertyController::edit
  requirements:
    slug: "[a-z0-9\\-]*"
  methods:    GET|POST
admin.property.delete:
  path: /admin/properties/{id}
  controller: App\Controller\Admin\PropertyController::delete
  methods:    DELETE